---
title: "Lesson Plan 4"
author: "Charles Jason Tinant"
date: "9/20/2018"
output:
  pdf_document: default
---

# Engr 233/231-Elementary Surveying Lesson Sheet
## Lesson 4 – Chapter 4 - Chapter 4 – Leveling, Theory, Methods, and Equipment

### Updates

Homework 3 is due Friday.  Please upload the assignment on theory of errors (Problems #: 3.2, 3.3, 3.4, 3.6, 3.15, 3.18 ) to the Google Scholar website.  


### Orientation: 
Leveling is used by engineers and surveyors to determine differences in elevation at different points. The processes used and results are especially important to engineers in design and construction of engineering projects. 

### Objectives:
1. Students should be familiar with the definitions related to the theory of elevations and leveling. 
2. Students should understand the historic development of NGVD29 and NAVD88. 
3. Students should be able to calculate the impact of curvature and refraction on leveling operations. 
4. Students should understand the theory, be able to apply the principles for gathering field data, and be able to calculate results for differential and trigonometric leveling from field or supplied data. 

### Reading Assignment:  
*Ghilani and Wolf Chapter 4 – Leveling, Theory, Methods, and Equipment*  
**Read carefully** sections 4.2, 4.5.1, 4.5.2, 4.5.4, 4.15.5  
Read sections 4.3, 4.4, 4.5
Scan sections on equipment  
  
### In-Class Assignment: 
See below


### HOMEWORK ASSIGNMENT 
**Due Date:** September 28, 2018
**answers to selected problems are in Appendix G of the text**
Problems 2, 6, 12, 15, 28

### Suggested Class Schedule   
0:00 - Class Start & Discuss Questions  
0:20 – Discuss definitions on pages 70-72   
0:40 - Discuss North American Vertical Datum  
0:50 – Break   
1:20 – Discuss curvature and refraction
1:40 - Begin differential leveling discussion
1:50 – Break    
2:00 – Trigonometric leveling & in-class problems
2:50 – Class Discussion   

### Surveying laboratory
We are going to look for the datum & section marker & set up some benchmarks

Preparation for lab.  
1. See problem 4.3.  Download the benchmark for the station north of Kyle.  


```{r setup, message=FALSE}
library("tidyverse")  # the calculations below use commands and pipes
# that are collectively known as the 'tidyverse'.  
# you can download this group of packages by:
# install.packages("tidyverse")
```

# Lecture Notes 
1. Spend enough time with Figure 4.1 to understand leveling terms.  
2. Discuss the North American Vertical Datum.  
3. Understanding **curvature** and **refraction** is the key to understanding some important surveying techniques to minimize error.  *Curvature* describes departures between a horizontal surface and a level surface that cause an upward bias in reading a change in vertical distance. *Refraction*, the bending of light, causes light rays to bend towards the surface. This light bending causes sunsets to appear red. *The longest electomagnetic rays, red in the visible spectrum, are deflected least by diffraction causing red sunsets when the sun is below the horizion.*  The effects of refraction in an elevation survey are in the opposite direction of curvature and about $1/7$ the magnitude.  The calculations to determine the effects for curvature $C_f$ and refraction $R_f$ and combined effects $h_f$ are shown below.  Note that the calculation is shown for thousands of feet, and the text provides the calculation in SI units and miles.  

$$C_f = 0.0239F^2$$ 
$$R_f = 0.0033F^2$$
 $$h_f = 0.0206 F^2$$ 



